Bump submodule, add WHOX, reorganize groups in the spec list
ircv3/ircv3.github.io pull request #434
Opened 2022-02-23 00:03 UTC by progval

2022-02-24 11:21 UTC, emersion commented
soju can be added as both a client and server supporting WHOX. Other than that, LGTM!

2022-02-24 11:36 UTC, progval commented
Ah fair, I didn't check bouncers.

Though I don't see anything about soju explicitly WHOX as a client, it's just forwarding requests. Does this warrant a green tick here?

2022-02-24 11:39 UTC, emersion commented
Bouncers are just proxies, so not sure how we could better support the extension? e.g. how can a bouncer support MONITOR, away-notify, account-tag, other than properly forwarding the data?

2022-02-24 19:18 UTC, progval commented
Added both.

2022-02-24 19:27 UTC, emersion commented on _irc/index.md
> +details the exact messages these changes apply to and how exactly it's used.
This sentence was originally after the next one (which acted as a kind of introduction). Now this reads a bit weird. Maybe we could rejigger the text a bit?

2022-02-25 08:13 UTC, emersion approved these changes
LGTM!

2022-03-01 00:09 UTC, jwheare requested changes
Let's add the 354 numeric to the registry as well

2022-03-01 00:09 UTC, jwheare commented on README.md
>  5. Add the relevant support to the data files!
Misnumbered now.

2022-03-01 19:17 UTC, merged

2022-03-01 19:17 UTC, jwheare commented
Thank you!